<?php
/**
 * REST API Endpoints for ImagenFlow.
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

class ImagenFlow_REST_API {

	/**
	 * Constructor.
	 */
	public function __construct() {
		add_action( 'rest_api_init', array( $this, 'register_routes' ) );
	}

	/**
	 * Register REST API routes.
	 */
	public function register_routes() {
		register_rest_route( 'imagen-flow/v1', '/generate', array(
			'methods'             => 'POST',
			'callback'            => array( $this, 'generate_image' ),
			'permission_callback' => array( $this, 'check_permission' ),
		) );

		register_rest_route( 'imagen-flow/v1', '/analyze', array(
			'methods'             => 'POST',
			'callback'            => array( $this, 'analyze_image' ),
			'permission_callback' => array( $this, 'check_permission' ),
		) );

		register_rest_route( 'imagen-flow/v1', '/summarize', array(
			'methods'             => 'POST',
			'callback'            => array( $this, 'summarize_content' ),
			'permission_callback' => array( $this, 'check_permission' ),
		) );

		register_rest_route( 'imagen-flow/v1', '/debug-models', array(
			'methods'             => 'GET',
			'callback'            => array( $this, 'debug_models' ),
			'permission_callback' => '__return_true',
		) );
	}

	/**
	 * Check if user has permission to use the plugin.
	 */
	public function check_permission() {
		return current_user_can( 'edit_posts' );
	}

	/**
	 * Callback for image generation.
	 */
	public function generate_image( $request ) {
		$params  = $request->get_params();
		$prompt           = isset( $params['prompt'] ) ? sanitize_textarea_field( $params['prompt'] ) : '';
		$samples          = isset( $params['samples'] ) ? absint( $params['samples'] ) : 1;
		$filename_keyword = isset( $params['filename_keyword'] ) ? sanitize_text_field( $params['filename_keyword'] ) : '';
		$orientation      = isset( $params['orientation'] ) ? sanitize_text_field( $params['orientation'] ) : 'square';

		$aspect_ratio = '1:1';
		if ( 'landscape' === $orientation ) {
			$aspect_ratio = '16:9';
		} elseif ( 'portrait' === $orientation ) {
			$aspect_ratio = '9:16';
		}

		if ( empty( $prompt ) ) {
			return new WP_Error( 'missing_prompt', 'Prompt is required.', array( 'status' => 400 ) );
		}

		$api    = new ImagenFlow_Gemini_API();
		$result = $api->generate_image( $prompt, array( 
			'sampleCount' => $samples,
			'aspectRatio' => $aspect_ratio
		) );

		if ( is_wp_error( $result ) ) {
			return $result;
		}

		// Process and sideload the images.
		$processor     = new ImagenFlow_Media_Processor();
		$attachment_ids = array();
		
		if ( isset( $result['predictions'] ) && is_array( $result['predictions'] ) ) {
			foreach ( $result['predictions'] as $index => $prediction ) {
				if ( isset( $prediction['bytesBase64Encoded'] ) ) {
					$image_data = base64_decode( $prediction['bytesBase64Encoded'] );
					
					if ( ! $image_data ) {
						continue;
					}

					$tmp_file = wp_tempnam( 'imagen_' . $index );
					file_put_contents( $tmp_file, $image_data );
					
					// Generate a dedicated concise Alt Text
					$alt_text = $api->generate_alt_text( $prompt, $filename_keyword );
					if ( is_wp_error( $alt_text ) ) {
						$alt_text = $prompt; // Fallback
					}

					// Construct filename: keyword + prompt snippet (natural) + random
					$name_parts = array();
					if ( ! empty( $filename_keyword ) ) {
						$name_parts[] = $filename_keyword;
					}
					
					// Get first 4 words of prompt, clean it up
					$prompt_words = explode( ' ', preg_replace( '/[^a-z0-9 ]/i', '', $prompt ) );
					$prompt_snippet = implode( '-', array_slice( array_filter( $prompt_words ), 0, 4 ) );
					
					if ( ! empty( $prompt_snippet ) ) {
						$name_parts[] = $prompt_snippet;
					}
					$name_parts[] = wp_generate_password( 4, false );

					$id = $processor->process_and_sideload( $tmp_file, array(
						'alt'      => $alt_text,
						'caption'  => 'Generated by AI',
						'filename' => implode( '-', $name_parts ),
					) );
					
					if ( ! is_wp_error( $id ) ) {
						error_log( "ImagenFlow: Successfully sideloaded image ID $id" );
						$attachment_ids[] = array(
							'id'  => $id,
							'url' => wp_get_attachment_url( $id ),
						);
					} else {
						error_log( 'ImagenFlow: Sideloading failed for prompt: ' . $id->get_error_message() );
					}
					
					@unlink( $tmp_file );
				} else {
					error_log( "ImagenFlow: Missing bytesBase64Encoded in prediction index $index" );
				}
			}
		} else {
			error_log( 'ImagenFlow: No predictions found in API response.' );
		}

		return rest_ensure_response( array(
			'success' => true,
			'images'  => $attachment_ids,
		) );
	}

	/**
	 * Callback for image analysis.
	 */
	public function analyze_image( $request ) {
		$params     = $request->get_params();
		$image_id   = isset( $params['image_id'] ) ? absint( $params['image_id'] ) : 0;
		$image_data = isset( $params['image_data'] ) ? $params['image_data'] : ''; // Base64 if not from media library

		if ( ! $image_id && ! $image_data ) {
			return new WP_Error( 'missing_image', 'Image data is required.', array( 'status' => 400 ) );
		}

		if ( $image_id ) {
			$path       = get_attached_file( $image_id );
			$image_data = base64_encode( file_get_contents( $path ) );
		}

		$api    = new ImagenFlow_Gemini_API();
		$result = $api->analyze_image( $image_data );

		if ( is_wp_error( $result ) ) {
			return $result;
		}

		return rest_ensure_response( array(
			'success'     => true,
			'description' => $result,
		) );
	}

	/**
	 * Callback for content summarization.
	 */
	public function summarize_content( $request ) {
		$params  = $request->get_params();
		$content = isset( $params['content'] ) ? wp_kses_post( $params['content'] ) : '';

		if ( empty( $content ) ) {
			return new WP_Error( 'missing_content', 'Content is required.', array( 'status' => 400 ) );
		}

		$api    = new ImagenFlow_Gemini_API();
		$result = $api->summarize_content( $content );

		if ( is_wp_error( $result ) ) {
			return $result;
		}

		return rest_ensure_response( array(
			'success' => true,
			'essence' => $result,
		) );
	}

	/**
	 * Debug endpoint to list models.
	 */
	public function debug_models() {
		$options = get_option( 'imagen_flow_options' );
		$api_key = isset( $options['gemini_api_key'] ) ? $options['gemini_api_key'] : '';
		$url = "https://generativelanguage.googleapis.com/v1beta/models?key=" . $api_key;
		
		$response = wp_remote_get( $url );
		if ( is_wp_error( $response ) ) {
			return $response;
		}

		return rest_ensure_response( json_decode( wp_remote_retrieve_body( $response ), true ) );
	}
}
